[package]
name = "ztbd-scrapper"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.70"
lazy_static = "1.4.0"
reqwest = "0.11.14"
scraper = "0.15.0"
thiserror = "1.0.40"
tokio = { version = "1.26.0", features = ["full"] }
